kind: Pod
apiVersion: v1
metadata:
  name: db2
spec:
  containers:
  - image: registry.access.redhat.com/rhscl/mysql-80-rhel7:8.0-162
    name: db1
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: secret1
            key: MYSQL_ROOT_PASSWORD
